# Generated by Django 5.0.6 on 2024-07-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
