name: CI/CD for Django Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10.12", "3.12.0" ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black check
        run: black --check .

      - name: Config env
        run: cp env_template .env

      - name: Run tests
        run: pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: success()

    steps:
      - name: Start the project with the latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.ECS_HOST }}
          username: ${{ vars.ECS_USER }}
          key: ${{ secrets.ECS_KEY }}
          script: |
            if [ ! -d "${{ vars.ECS_PATH }}" ]; then
              git clone git@github.com:wrist-check/wc-miniprogram-api.git ${{ vars.ECS_PATH }}
            else
              cd ${{ vars.ECS_PATH }}
              git fetch origin
              git reset --hard origin/main
            fi
            
            cd ${{ vars.ECS_PATH }}
            cat <<EOF > .env
            ENVIRONMENT=${{ vars.ENVIRONMENT }}
            PORT=${{ vars.PORT }}
            ALLOWED_HOSTS=${{ vars.ALLOWED_HOSTS }}
            CSRF_TRUSTED_ORIGINS=${{ vars.CSRF_TRUSTED_ORIGINS }}
            CORS_ALLOWED_ORIGINS=${{ vars.CORS_ALLOWED_ORIGINS }}
            WECHAT_MINI_GET_SESSION_KEY_URL=${{ vars.WECHAT_MINI_GET_SESSION_KEY_URL }}
            WECHAT_MINI_APPID=${{ secrets.WECHAT_MINI_APPID }}
            WECHAT_MINI_SECRET=${{ secrets.WECHAT_MINI_SECRET }}
            EOF
            
            make migrate
            make collectstatic
            supervisorctl restart wristcheck
